from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(900, 530)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        Dialog.setPalette(palette)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("data/assets/main_add_event.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setAutoFillBackground(True)
        Dialog.setModal(True)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(0, 0, 320, 531))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.frame.setPalette(palette)
        self.frame.setAutoFillBackground(True)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lbl_caption = QtWidgets.QLabel(self.frame)
        self.lbl_caption.setGeometry(QtCore.QRect(20, 40, 291, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lbl_caption.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.lbl_caption.setFont(font)
        self.lbl_caption.setObjectName("lbl_caption")
        self.lbl_main_wallet = QtWidgets.QLabel(self.frame)
        self.lbl_main_wallet.setGeometry(QtCore.QRect(40, 150, 271, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lbl_main_wallet.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setUnderline(False)
        self.lbl_main_wallet.setFont(font)
        self.lbl_main_wallet.setObjectName("lbl_main_wallet")
        self.lbl_user = QtWidgets.QLabel(self.frame)
        self.lbl_user.setGeometry(QtCore.QRect(40, 180, 271, 71))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lbl_user.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setUnderline(False)
        self.lbl_user.setFont(font)
        self.lbl_user.setWordWrap(True)
        self.lbl_user.setObjectName("lbl_user")
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setGeometry(QtCore.QRect(20, 110, 280, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        self.line.setPalette(palette)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.lbl_app = QtWidgets.QLabel(self.frame)
        self.lbl_app.setGeometry(QtCore.QRect(20, 293, 291, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lbl_app.setPalette(palette)
        self.lbl_app.setObjectName("lbl_app")
        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setGeometry(QtCore.QRect(20, 330, 280, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        self.line_2.setPalette(palette)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.lbl_items = QtWidgets.QLabel(self.frame)
        self.lbl_items.setGeometry(QtCore.QRect(20, 370, 261, 141))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lbl_items.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setUnderline(False)
        self.lbl_items.setFont(font)
        self.lbl_items.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_items.setWordWrap(True)
        self.lbl_items.setObjectName("lbl_items")
        self.lbl_income_rsd = QtWidgets.QLabel(Dialog)
        self.lbl_income_rsd.setGeometry(QtCore.QRect(320, 20, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_income_rsd.setFont(font)
        self.lbl_income_rsd.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_income_rsd.setObjectName("lbl_income_rsd")
        self.txt_income_rsd = QtWidgets.QLineEdit(Dialog)
        self.txt_income_rsd.setGeometry(QtCore.QRect(470, 20, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txt_income_rsd.setFont(font)
        self.txt_income_rsd.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txt_income_rsd.setObjectName("txt_income_rsd")
        self.txt_outcome_rsd = QtWidgets.QLineEdit(Dialog)
        self.txt_outcome_rsd.setGeometry(QtCore.QRect(470, 60, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txt_outcome_rsd.setFont(font)
        self.txt_outcome_rsd.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txt_outcome_rsd.setObjectName("txt_outcome_rsd")
        self.lbl_outcome_rsd = QtWidgets.QLabel(Dialog)
        self.lbl_outcome_rsd.setGeometry(QtCore.QRect(320, 60, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_outcome_rsd.setFont(font)
        self.lbl_outcome_rsd.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_outcome_rsd.setObjectName("lbl_outcome_rsd")
        self.txt_outcome_eur = QtWidgets.QLineEdit(Dialog)
        self.txt_outcome_eur.setGeometry(QtCore.QRect(730, 60, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txt_outcome_eur.setFont(font)
        self.txt_outcome_eur.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txt_outcome_eur.setObjectName("txt_outcome_eur")
        self.lbl_outcome_eur = QtWidgets.QLabel(Dialog)
        self.lbl_outcome_eur.setGeometry(QtCore.QRect(580, 60, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_outcome_eur.setFont(font)
        self.lbl_outcome_eur.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_outcome_eur.setObjectName("lbl_outcome_eur")
        self.txt_income_eur = QtWidgets.QLineEdit(Dialog)
        self.txt_income_eur.setGeometry(QtCore.QRect(730, 20, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txt_income_eur.setFont(font)
        self.txt_income_eur.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txt_income_eur.setObjectName("txt_income_eur")
        self.lbl_income_eur = QtWidgets.QLabel(Dialog)
        self.lbl_income_eur.setGeometry(QtCore.QRect(580, 20, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_income_eur.setFont(font)
        self.lbl_income_eur.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_income_eur.setObjectName("lbl_income_eur")
        self.lbl_date = QtWidgets.QLabel(Dialog)
        self.lbl_date.setGeometry(QtCore.QRect(320, 110, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_date.setFont(font)
        self.lbl_date.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_date.setObjectName("lbl_date")
        self.txt_description = QtWidgets.QLineEdit(Dialog)
        self.txt_description.setGeometry(QtCore.QRect(430, 250, 461, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txt_description.setFont(font)
        self.txt_description.setObjectName("txt_description")
        self.lbl_description = QtWidgets.QLabel(Dialog)
        self.lbl_description.setGeometry(QtCore.QRect(320, 250, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_description.setFont(font)
        self.lbl_description.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_description.setObjectName("lbl_description")
        self.lbl_event_type = QtWidgets.QLabel(Dialog)
        self.lbl_event_type.setGeometry(QtCore.QRect(550, 110, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_event_type.setFont(font)
        self.lbl_event_type.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_event_type.setObjectName("lbl_event_type")
        self.cmb_event_type = QtWidgets.QComboBox(Dialog)
        self.cmb_event_type.setGeometry(QtCore.QRect(690, 110, 201, 31))
        self.cmb_event_type.setObjectName("cmb_event_type")
        self.lbl_place = QtWidgets.QLabel(Dialog)
        self.lbl_place.setGeometry(QtCore.QRect(550, 170, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_place.setFont(font)
        self.lbl_place.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_place.setObjectName("lbl_place")
        self.cmb_place = QtWidgets.QComboBox(Dialog)
        self.cmb_place.setGeometry(QtCore.QRect(690, 170, 201, 31))
        self.cmb_place.setObjectName("cmb_place")
        self.btn_new_event_type = QtWidgets.QPushButton(Dialog)
        self.btn_new_event_type.setGeometry(QtCore.QRect(830, 140, 61, 21))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("data/assets/new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_new_event_type.setIcon(icon1)
        self.btn_new_event_type.setIconSize(QtCore.QSize(20, 18))
        self.btn_new_event_type.setObjectName("btn_new_event_type")
        self.btn_new_place = QtWidgets.QPushButton(Dialog)
        self.btn_new_place.setGeometry(QtCore.QRect(830, 200, 61, 21))
        self.btn_new_place.setIcon(icon1)
        self.btn_new_place.setIconSize(QtCore.QSize(20, 18))
        self.btn_new_place.setObjectName("btn_new_place")
        self.btn_cancel = QtWidgets.QPushButton(Dialog)
        self.btn_cancel.setGeometry(QtCore.QRect(790, 290, 101, 31))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("data/assets/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_cancel.setIcon(icon2)
        self.btn_cancel.setObjectName("btn_cancel")
        self.btn_save = QtWidgets.QPushButton(Dialog)
        self.btn_save.setGeometry(QtCore.QRect(680, 290, 101, 31))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("data/assets/ok.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_save.setIcon(icon3)
        self.btn_save.setObjectName("btn_save")
        self.dt_date = QtWidgets.QDateEdit(Dialog)
        self.dt_date.setGeometry(QtCore.QRect(430, 110, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.dt_date.setFont(font)
        self.dt_date.setObjectName("dt_date")
        self.btn_date_pick = QtWidgets.QPushButton(Dialog)
        self.btn_date_pick.setGeometry(QtCore.QRect(510, 140, 71, 21))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("data/assets/calendar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_date_pick.setIcon(icon4)
        self.btn_date_pick.setIconSize(QtCore.QSize(22, 18))
        self.btn_date_pick.setObjectName("btn_date_pick")
        self.tbl_items = QtWidgets.QTableWidget(Dialog)
        self.tbl_items.setGeometry(QtCore.QRect(330, 330, 560, 190))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.NoRole, brush)
        self.tbl_items.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tbl_items.setFont(font)
        self.tbl_items.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tbl_items.setObjectName("tbl_items")
        self.tbl_items.setColumnCount(0)
        self.tbl_items.setRowCount(0)
        self.btn_add = QtWidgets.QPushButton(Dialog)
        self.btn_add.setGeometry(QtCore.QRect(330, 290, 101, 31))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("data/assets/arrow_down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_add.setIcon(icon5)
        self.btn_add.setObjectName("btn_add")
        self.txt_exchange = QtWidgets.QLineEdit(Dialog)
        self.txt_exchange.setGeometry(QtCore.QRect(470, 170, 111, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txt_exchange.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txt_exchange.setFont(font)
        self.txt_exchange.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txt_exchange.setObjectName("txt_exchange")
        self.lbl_exchange = QtWidgets.QLabel(Dialog)
        self.lbl_exchange.setGeometry(QtCore.QRect(330, 160, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_exchange.setFont(font)
        self.lbl_exchange.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_exchange.setWordWrap(True)
        self.lbl_exchange.setObjectName("lbl_exchange")
        self.lbl_partner = QtWidgets.QLabel(Dialog)
        self.lbl_partner.setGeometry(QtCore.QRect(330, 210, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_partner.setFont(font)
        self.lbl_partner.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_partner.setObjectName("lbl_partner")
        self.cmb_partner = QtWidgets.QComboBox(Dialog)
        self.cmb_partner.setGeometry(QtCore.QRect(470, 210, 221, 31))
        self.cmb_partner.setEditable(True)
        self.cmb_partner.setObjectName("cmb_partner")

        self.txt_income_rsd.returnPressed.connect(self.txt_outcome_rsd.setFocus)
        self.txt_income_rsd.returnPressed.connect(self.txt_outcome_rsd.selectAll)
        self.txt_outcome_rsd.returnPressed.connect(self.txt_description.setFocus)
        self.txt_description.returnPressed.connect(self.txt_income_rsd.setFocus)
        self.txt_description.returnPressed.connect(self.txt_income_rsd.selectAll)
        self.txt_outcome_rsd.returnPressed.connect(self.txt_description.selectAll)
        self.btn_add.clicked['bool'].connect(self.txt_income_rsd.setFocus)
        self.btn_add.clicked['bool'].connect(self.txt_income_rsd.selectAll)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.txt_income_rsd, self.txt_outcome_rsd)
        Dialog.setTabOrder(self.txt_outcome_rsd, self.txt_income_eur)
        Dialog.setTabOrder(self.txt_income_eur, self.txt_outcome_eur)
        Dialog.setTabOrder(self.txt_outcome_eur, self.dt_date)
        Dialog.setTabOrder(self.dt_date, self.cmb_event_type)
        Dialog.setTabOrder(self.cmb_event_type, self.cmb_place)
        Dialog.setTabOrder(self.cmb_place, self.txt_exchange)
        Dialog.setTabOrder(self.txt_exchange, self.cmb_partner)
        Dialog.setTabOrder(self.cmb_partner, self.txt_description)
        Dialog.setTabOrder(self.txt_description, self.btn_add)
        Dialog.setTabOrder(self.btn_add, self.tbl_items)
        Dialog.setTabOrder(self.tbl_items, self.btn_save)
        Dialog.setTabOrder(self.btn_save, self.btn_cancel)
        Dialog.setTabOrder(self.btn_cancel, self.btn_new_event_type)
        Dialog.setTabOrder(self.btn_new_event_type, self.btn_new_place)
        Dialog.setTabOrder(self.btn_new_place, self.btn_date_pick)
