from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(590, 345)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        Dialog.setPalette(palette)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("data/assets/graph.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.lbl_saved_charts = QtWidgets.QLabel(Dialog)
        self.lbl_saved_charts.setGeometry(QtCore.QRect(10, 10, 351, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_saved_charts.setFont(font)
        self.lbl_saved_charts.setObjectName("lbl_saved_charts")
        self.btn_show = QtWidgets.QPushButton(Dialog)
        self.btn_show.setGeometry(QtCore.QRect(380, 90, 201, 41))
        self.btn_show.setIcon(icon)
        self.btn_show.setIconSize(QtCore.QSize(30, 30))
        self.btn_show.setAutoDefault(False)
        self.btn_show.setDefault(True)
        self.btn_show.setObjectName("btn_show")
        self.btn_delete = QtWidgets.QPushButton(Dialog)
        self.btn_delete.setGeometry(QtCore.QRect(262, 310, 111, 28))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("data/assets/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_delete.setIcon(icon1)
        self.btn_delete.setAutoDefault(False)
        self.btn_delete.setObjectName("btn_delete")
        self.btn_rename = QtWidgets.QPushButton(Dialog)
        self.btn_rename.setGeometry(QtCore.QRect(140, 310, 111, 28))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("data/assets/rename.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_rename.setIcon(icon2)
        self.btn_rename.setAutoDefault(False)
        self.btn_rename.setObjectName("btn_rename")
        self.btn_add = QtWidgets.QPushButton(Dialog)
        self.btn_add.setGeometry(QtCore.QRect(430, 140, 111, 28))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("data/assets/chart_setting.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_add.setIcon(icon3)
        self.btn_add.setAutoDefault(False)
        self.btn_add.setObjectName("btn_add")
        self.lbl_description = QtWidgets.QLabel(Dialog)
        self.lbl_description.setGeometry(QtCore.QRect(380, 190, 201, 111))
        self.lbl_description.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_description.setWordWrap(True)
        self.lbl_description.setObjectName("lbl_description")
        self.btn_edit = QtWidgets.QPushButton(Dialog)
        self.btn_edit.setGeometry(QtCore.QRect(10, 310, 91, 28))
        self.btn_edit.setIcon(icon3)
        self.btn_edit.setAutoDefault(False)
        self.btn_edit.setObjectName("btn_edit")
        self.lst_charts = QtWidgets.QListWidget(Dialog)
        self.lst_charts.setGeometry(QtCore.QRect(10, 60, 360, 240))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(131, 197, 197))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(131, 197, 197))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        self.lst_charts.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lst_charts.setFont(font)
        self.lst_charts.setStyleSheet("selection-background-color: rgb(170, 255, 127);\n"
"selection-color: rgb(0, 0, 127);")
        self.lst_charts.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.lst_charts.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.lst_charts.setWordWrap(True)
        self.lst_charts.setObjectName("lst_charts")

        QtCore.QMetaObject.connectSlotsByName(Dialog)
