from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1200, 640)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("data/assets/chart_setting.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.frm_chart_edit = QtWidgets.QFrame(Dialog)
        self.frm_chart_edit.setGeometry(QtCore.QRect(0, 0, 1201, 641))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(199, 199, 199))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(199, 199, 199))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(199, 199, 199))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(199, 199, 199))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.frm_chart_edit.setPalette(palette)
        self.frm_chart_edit.setAutoFillBackground(True)
        self.frm_chart_edit.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_chart_edit.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_chart_edit.setObjectName("frm_chart_edit")
        self.grp_organization = QtWidgets.QGroupBox(self.frm_chart_edit)
        self.grp_organization.setGeometry(QtCore.QRect(180, 10, 1011, 401))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.grp_organization.setPalette(palette)
        self.grp_organization.setAutoFillBackground(True)
        self.grp_organization.setObjectName("grp_organization")
        self.chk_event_type = QtWidgets.QCheckBox(self.grp_organization)
        self.chk_event_type.setGeometry(QtCore.QRect(20, 30, 251, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.chk_event_type.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.chk_event_type.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("data/assets/main_add_event_type.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.chk_event_type.setIcon(icon1)
        self.chk_event_type.setObjectName("chk_event_type")
        self.btn_event_type_select_all = QtWidgets.QPushButton(self.grp_organization)
        self.btn_event_type_select_all.setGeometry(QtCore.QRect(20, 280, 93, 28))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("data/assets/select_all.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_event_type_select_all.setIcon(icon2)
        self.btn_event_type_select_all.setAutoDefault(False)
        self.btn_event_type_select_all.setObjectName("btn_event_type_select_all")
        self.btn_event_type_clear_all = QtWidgets.QPushButton(self.grp_organization)
        self.btn_event_type_clear_all.setGeometry(QtCore.QRect(120, 280, 93, 28))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("data/assets/clear_all.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_event_type_clear_all.setIcon(icon3)
        self.btn_event_type_clear_all.setIconSize(QtCore.QSize(16, 16))
        self.btn_event_type_clear_all.setAutoDefault(False)
        self.btn_event_type_clear_all.setObjectName("btn_event_type_clear_all")
        self.btn_location_clear_all = QtWidgets.QPushButton(self.grp_organization)
        self.btn_location_clear_all.setGeometry(QtCore.QRect(660, 280, 93, 28))
        self.btn_location_clear_all.setIcon(icon3)
        self.btn_location_clear_all.setIconSize(QtCore.QSize(16, 16))
        self.btn_location_clear_all.setAutoDefault(False)
        self.btn_location_clear_all.setObjectName("btn_location_clear_all")
        self.btn_location_select_all = QtWidgets.QPushButton(self.grp_organization)
        self.btn_location_select_all.setGeometry(QtCore.QRect(560, 280, 93, 28))
        self.btn_location_select_all.setIcon(icon2)
        self.btn_location_select_all.setAutoDefault(False)
        self.btn_location_select_all.setObjectName("btn_location_select_all")
        self.chk_location = QtWidgets.QCheckBox(self.grp_organization)
        self.chk_location.setGeometry(QtCore.QRect(560, 30, 251, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.chk_location.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.chk_location.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("data/assets/main_location.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.chk_location.setIcon(icon4)
        self.chk_location.setObjectName("chk_location")
        self.txt_event_type_filter = QtWidgets.QLineEdit(self.grp_organization)
        self.txt_event_type_filter.setGeometry(QtCore.QRect(20, 60, 220, 25))
        self.txt_event_type_filter.setObjectName("txt_event_type_filter")
        self.btn_event_type_filter_apply = QtWidgets.QPushButton(self.grp_organization)
        self.btn_event_type_filter_apply.setGeometry(QtCore.QRect(240, 60, 35, 25))
        self.btn_event_type_filter_apply.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("data/assets/apply.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_event_type_filter_apply.setIcon(icon5)
        self.btn_event_type_filter_apply.setIconSize(QtCore.QSize(22, 22))
        self.btn_event_type_filter_apply.setAutoDefault(False)
        self.btn_event_type_filter_apply.setObjectName("btn_event_type_filter_apply")
        self.btn_location_filter_apply = QtWidgets.QPushButton(self.grp_organization)
        self.btn_location_filter_apply.setGeometry(QtCore.QRect(780, 60, 35, 25))
        self.btn_location_filter_apply.setText("")
        self.btn_location_filter_apply.setIcon(icon5)
        self.btn_location_filter_apply.setIconSize(QtCore.QSize(22, 22))
        self.btn_location_filter_apply.setAutoDefault(False)
        self.btn_location_filter_apply.setObjectName("btn_location_filter_apply")
        self.txt_location_filter = QtWidgets.QLineEdit(self.grp_organization)
        self.txt_location_filter.setGeometry(QtCore.QRect(560, 60, 220, 25))
        self.txt_location_filter.setObjectName("txt_location_filter")
        self.btn_partner_select_all = QtWidgets.QPushButton(self.grp_organization)
        self.btn_partner_select_all.setGeometry(QtCore.QRect(290, 280, 93, 28))
        self.btn_partner_select_all.setIcon(icon2)
        self.btn_partner_select_all.setAutoDefault(False)
        self.btn_partner_select_all.setObjectName("btn_partner_select_all")
        self.btn_partner_clear_all = QtWidgets.QPushButton(self.grp_organization)
        self.btn_partner_clear_all.setGeometry(QtCore.QRect(390, 280, 93, 28))
        self.btn_partner_clear_all.setIcon(icon3)
        self.btn_partner_clear_all.setIconSize(QtCore.QSize(16, 16))
        self.btn_partner_clear_all.setAutoDefault(False)
        self.btn_partner_clear_all.setObjectName("btn_partner_clear_all")
        self.btn_partner_filter_apply = QtWidgets.QPushButton(self.grp_organization)
        self.btn_partner_filter_apply.setGeometry(QtCore.QRect(510, 60, 35, 25))
        self.btn_partner_filter_apply.setText("")
        self.btn_partner_filter_apply.setIcon(icon5)
        self.btn_partner_filter_apply.setIconSize(QtCore.QSize(22, 22))
        self.btn_partner_filter_apply.setAutoDefault(False)
        self.btn_partner_filter_apply.setObjectName("btn_partner_filter_apply")
        self.txt_partner_filter = QtWidgets.QLineEdit(self.grp_organization)
        self.txt_partner_filter.setGeometry(QtCore.QRect(290, 60, 220, 25))
        self.txt_partner_filter.setObjectName("txt_partner_filter")
        self.chk_partner = QtWidgets.QCheckBox(self.grp_organization)
        self.chk_partner.setGeometry(QtCore.QRect(290, 30, 251, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.chk_partner.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.chk_partner.setFont(font)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("data/assets/partner.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.chk_partner.setIcon(icon6)
        self.chk_partner.setObjectName("chk_partner")
        self.lbl_group_by = QtWidgets.QLabel(self.grp_organization)
        self.lbl_group_by.setGeometry(QtCore.QRect(840, 70, 160, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lbl_group_by.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_group_by.setFont(font)
        self.lbl_group_by.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_group_by.setObjectName("lbl_group_by")
        self.rdb_dates = QtWidgets.QRadioButton(self.grp_organization)
        self.rdb_dates.setGeometry(QtCore.QRect(840, 120, 160, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rdb_dates.setFont(font)
        self.rdb_dates.setObjectName("rdb_dates")
        self.rdb_weeks = QtWidgets.QRadioButton(self.grp_organization)
        self.rdb_weeks.setGeometry(QtCore.QRect(840, 160, 160, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rdb_weeks.setFont(font)
        self.rdb_weeks.setObjectName("rdb_weeks")
        self.rdb_months = QtWidgets.QRadioButton(self.grp_organization)
        self.rdb_months.setGeometry(QtCore.QRect(840, 200, 160, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rdb_months.setFont(font)
        self.rdb_months.setObjectName("rdb_months")
        self.rdb_years = QtWidgets.QRadioButton(self.grp_organization)
        self.rdb_years.setGeometry(QtCore.QRect(840, 240, 160, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rdb_years.setFont(font)
        self.rdb_years.setObjectName("rdb_years")
        self.lbl_info = QtWidgets.QLabel(self.grp_organization)
        self.lbl_info.setGeometry(QtCore.QRect(10, 330, 991, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lbl_info.setPalette(palette)
        self.lbl_info.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.lbl_info.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lbl_info.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_info.setWordWrap(True)
        self.lbl_info.setObjectName("lbl_info")
        self.lst_event_type = QtWidgets.QListWidget(self.grp_organization)
        self.lst_event_type.setGeometry(QtCore.QRect(20, 90, 255, 192))
        self.lst_event_type.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.lst_event_type.setWordWrap(True)
        self.lst_event_type.setObjectName("lst_event_type")
        self.lst_partner = QtWidgets.QListWidget(self.grp_organization)
        self.lst_partner.setGeometry(QtCore.QRect(290, 90, 255, 192))
        self.lst_partner.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.lst_partner.setWordWrap(True)
        self.lst_partner.setObjectName("lst_partner")
        self.lst_location = QtWidgets.QListWidget(self.grp_organization)
        self.lst_location.setGeometry(QtCore.QRect(560, 90, 255, 192))
        self.lst_location.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.lst_location.setWordWrap(True)
        self.lst_location.setObjectName("lst_location")
        self.lbl_chart_edit = QtWidgets.QLabel(self.frm_chart_edit)
        self.lbl_chart_edit.setGeometry(QtCore.QRect(10, 20, 161, 111))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lbl_chart_edit.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_chart_edit.setFont(font)
        self.lbl_chart_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_chart_edit.setWordWrap(True)
        self.lbl_chart_edit.setObjectName("lbl_chart_edit")
        self.lbl_chart_name = QtWidgets.QLabel(self.frm_chart_edit)
        self.lbl_chart_name.setGeometry(QtCore.QRect(10, 140, 161, 21))
        self.lbl_chart_name.setObjectName("lbl_chart_name")
        self.btn_save = QtWidgets.QPushButton(self.frm_chart_edit)
        self.btn_save.setGeometry(QtCore.QRect(970, 600, 93, 28))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("data/assets/ok.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_save.setIcon(icon7)
        self.btn_save.setAutoDefault(False)
        self.btn_save.setObjectName("btn_save")
        self.btn_preview = QtWidgets.QPushButton(self.frm_chart_edit)
        self.btn_preview.setGeometry(QtCore.QRect(5, 340, 170, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_preview.setFont(font)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("data/assets/graph.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_preview.setIcon(icon8)
        self.btn_preview.setIconSize(QtCore.QSize(35, 35))
        self.btn_preview.setAutoDefault(False)
        self.btn_preview.setObjectName("btn_preview")
        self.grp_design = QtWidgets.QGroupBox(self.frm_chart_edit)
        self.grp_design.setGeometry(QtCore.QRect(10, 420, 1181, 161))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.grp_design.setPalette(palette)
        self.grp_design.setObjectName("grp_design")
        self.txt_headline = QtWidgets.QTextEdit(self.grp_design)
        self.txt_headline.setGeometry(QtCore.QRect(10, 45, 391, 70))
        self.txt_headline.setObjectName("txt_headline")
        self.btn_headline_font = QtWidgets.QPushButton(self.grp_design)
        self.btn_headline_font.setGeometry(QtCore.QRect(310, 120, 93, 28))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("data/assets/font.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_headline_font.setIcon(icon9)
        self.btn_headline_font.setAutoDefault(False)
        self.btn_headline_font.setObjectName("btn_headline_font")
        self.btn_headline_color = QtWidgets.QPushButton(self.grp_design)
        self.btn_headline_color.setGeometry(QtCore.QRect(210, 120, 93, 28))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("data/assets/color.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_headline_color.setIcon(icon10)
        self.btn_headline_color.setAutoDefault(False)
        self.btn_headline_color.setObjectName("btn_headline_color")
        self.lbl_headline = QtWidgets.QLabel(self.grp_design)
        self.lbl_headline.setGeometry(QtCore.QRect(10, 20, 391, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lbl_headline.setPalette(palette)
        self.lbl_headline.setObjectName("lbl_headline")
        self.btn_x_axis_color = QtWidgets.QPushButton(self.grp_design)
        self.btn_x_axis_color.setGeometry(QtCore.QRect(460, 120, 93, 28))
        self.btn_x_axis_color.setIcon(icon10)
        self.btn_x_axis_color.setAutoDefault(False)
        self.btn_x_axis_color.setObjectName("btn_x_axis_color")
        self.lbl_x_axis = QtWidgets.QLabel(self.grp_design)
        self.lbl_x_axis.setGeometry(QtCore.QRect(420, 20, 231, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lbl_x_axis.setPalette(palette)
        self.lbl_x_axis.setObjectName("lbl_x_axis")
        self.btn_x_axis_font = QtWidgets.QPushButton(self.grp_design)
        self.btn_x_axis_font.setGeometry(QtCore.QRect(560, 120, 93, 28))
        self.btn_x_axis_font.setIcon(icon9)
        self.btn_x_axis_font.setAutoDefault(False)
        self.btn_x_axis_font.setObjectName("btn_x_axis_font")
        self.btn_y_axis_font = QtWidgets.QPushButton(self.grp_design)
        self.btn_y_axis_font.setGeometry(QtCore.QRect(800, 120, 93, 28))
        self.btn_y_axis_font.setIcon(icon9)
        self.btn_y_axis_font.setAutoDefault(False)
        self.btn_y_axis_font.setObjectName("btn_y_axis_font")
        self.btn_y_axis_color = QtWidgets.QPushButton(self.grp_design)
        self.btn_y_axis_color.setGeometry(QtCore.QRect(700, 120, 93, 28))
        self.btn_y_axis_color.setIcon(icon10)
        self.btn_y_axis_color.setAutoDefault(False)
        self.btn_y_axis_color.setObjectName("btn_y_axis_color")
        self.lbl_y_axis = QtWidgets.QLabel(self.grp_design)
        self.lbl_y_axis.setGeometry(QtCore.QRect(670, 20, 221, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lbl_y_axis.setPalette(palette)
        self.lbl_y_axis.setObjectName("lbl_y_axis")
        self.lbl_pic = QtWidgets.QLabel(self.grp_design)
        self.lbl_pic.setGeometry(QtCore.QRect(910, 50, 100, 100))
        self.lbl_pic.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_pic.setText("")
        self.lbl_pic.setPixmap(QtGui.QPixmap("data/assets/chart_line.png"))
        self.lbl_pic.setScaledContents(True)
        self.lbl_pic.setObjectName("lbl_pic")
        self.rdb_bars = QtWidgets.QRadioButton(self.grp_design)
        self.rdb_bars.setGeometry(QtCore.QRect(910, 20, 80, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.rdb_bars.setPalette(palette)
        self.rdb_bars.setObjectName("rdb_bars")
        self.rdb_lines = QtWidgets.QRadioButton(self.grp_design)
        self.rdb_lines.setGeometry(QtCore.QRect(1000, 20, 80, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.rdb_lines.setPalette(palette)
        self.rdb_lines.setObjectName("rdb_lines")
        self.btn_chart_color = QtWidgets.QPushButton(self.grp_design)
        self.btn_chart_color.setGeometry(QtCore.QRect(1069, 50, 101, 31))
        self.btn_chart_color.setIcon(icon10)
        self.btn_chart_color.setAutoDefault(False)
        self.btn_chart_color.setObjectName("btn_chart_color")
        self.cmb_chart_marker = QtWidgets.QComboBox(self.grp_design)
        self.cmb_chart_marker.setGeometry(QtCore.QRect(1020, 85, 150, 31))
        self.cmb_chart_marker.setObjectName("cmb_chart_marker")
        self.cmb_chart_pattern = QtWidgets.QComboBox(self.grp_design)
        self.cmb_chart_pattern.setGeometry(QtCore.QRect(1020, 120, 150, 31))
        self.cmb_chart_pattern.setObjectName("cmb_chart_pattern")
        self.lbl_graph_color = QtWidgets.QLabel(self.grp_design)
        self.lbl_graph_color.setGeometry(QtCore.QRect(1020, 50, 41, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.lbl_graph_color.setPalette(palette)
        self.lbl_graph_color.setAutoFillBackground(False)
        self.lbl_graph_color.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.lbl_graph_color.setText("")
        self.lbl_graph_color.setObjectName("lbl_graph_color")
        self.txt_y_axis = QtWidgets.QLineEdit(self.grp_design)
        self.txt_y_axis.setGeometry(QtCore.QRect(670, 85, 221, 31))
        self.txt_y_axis.setObjectName("txt_y_axis")
        self.cmb_y_axis = QtWidgets.QComboBox(self.grp_design)
        self.cmb_y_axis.setGeometry(QtCore.QRect(670, 50, 221, 31))
        self.cmb_y_axis.setObjectName("cmb_y_axis")
        self.rdb_pies = QtWidgets.QRadioButton(self.grp_design)
        self.rdb_pies.setGeometry(QtCore.QRect(1090, 20, 80, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.rdb_pies.setPalette(palette)
        self.rdb_pies.setObjectName("rdb_pies")
        self.txt_x_axis = QtWidgets.QLineEdit(self.grp_design)
        self.txt_x_axis.setGeometry(QtCore.QRect(420, 50, 231, 71))
        self.txt_x_axis.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_x_axis.setObjectName("txt_x_axis")
        self.btn_cancel = QtWidgets.QPushButton(self.frm_chart_edit)
        self.btn_cancel.setGeometry(QtCore.QRect(1080, 600, 93, 28))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("data/assets/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_cancel.setIcon(icon11)
        self.btn_cancel.setAutoDefault(False)
        self.btn_cancel.setObjectName("btn_cancel")
        self.lbl_chart_description = QtWidgets.QLabel(self.frm_chart_edit)
        self.lbl_chart_description.setGeometry(QtCore.QRect(10, 215, 161, 21))
        self.lbl_chart_description.setObjectName("lbl_chart_description")
        self.txt_name = QtWidgets.QLineEdit(self.frm_chart_edit)
        self.txt_name.setGeometry(QtCore.QRect(5, 165, 171, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(199, 199, 199))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txt_name.setPalette(palette)
        self.txt_name.setAutoFillBackground(True)
        self.txt_name.setText("")
        self.txt_name.setObjectName("txt_name")
        self.txt_description = QtWidgets.QTextEdit(self.frm_chart_edit)
        self.txt_description.setGeometry(QtCore.QRect(5, 240, 171, 87))
        self.txt_description.setObjectName("txt_description")

        QtCore.QMetaObject.connectSlotsByName(Dialog)
