from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.NonModal)
        Dialog.resize(957, 500)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        Dialog.setPalette(palette)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("data/assets/main_add_event.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(0, 0, 310, 500))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.frame.setPalette(palette)
        self.frame.setAutoFillBackground(True)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lbl_event_id = QtWidgets.QLabel(self.frame)
        self.lbl_event_id.setGeometry(QtCore.QRect(10, 20, 291, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lbl_event_id.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_event_id.setFont(font)
        self.lbl_event_id.setObjectName("lbl_event_id")
        self.lbl_user = QtWidgets.QLabel(self.frame)
        self.lbl_user.setGeometry(QtCore.QRect(10, 80, 291, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lbl_user.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_user.setFont(font)
        self.lbl_user.setObjectName("lbl_user")
        self.lbl_user_data = QtWidgets.QLabel(self.frame)
        self.lbl_user_data.setGeometry(QtCore.QRect(20, 110, 281, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lbl_user_data.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_user_data.setFont(font)
        self.lbl_user_data.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_user_data.setWordWrap(True)
        self.lbl_user_data.setObjectName("lbl_user_data")
        self.lbl_created = QtWidgets.QLabel(self.frame)
        self.lbl_created.setGeometry(QtCore.QRect(10, 190, 291, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lbl_created.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_created.setFont(font)
        self.lbl_created.setObjectName("lbl_created")
        self.lbl_created_data = QtWidgets.QLabel(self.frame)
        self.lbl_created_data.setGeometry(QtCore.QRect(10, 220, 291, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lbl_created_data.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_created_data.setFont(font)
        self.lbl_created_data.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_created_data.setObjectName("lbl_created_data")
        self.lbl_wallet_data = QtWidgets.QLabel(self.frame)
        self.lbl_wallet_data.setGeometry(QtCore.QRect(10, 310, 291, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lbl_wallet_data.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_wallet_data.setFont(font)
        self.lbl_wallet_data.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_wallet_data.setObjectName("lbl_wallet_data")
        self.lbl_wallet = QtWidgets.QLabel(self.frame)
        self.lbl_wallet.setGeometry(QtCore.QRect(10, 280, 291, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lbl_wallet.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_wallet.setFont(font)
        self.lbl_wallet.setObjectName("lbl_wallet")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 301, 81))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 113))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 113))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 113))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 113))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.frame_2.setPalette(palette)
        self.frame_2.setAutoFillBackground(True)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.lbl_app = QtWidgets.QLabel(self.frame)
        self.lbl_app.setGeometry(QtCore.QRect(10, 475, 291, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lbl_app.setPalette(palette)
        self.lbl_app.setObjectName("lbl_app")
        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setGeometry(QtCore.QRect(10, 170, 280, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        self.line_2.setPalette(palette)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.frame)
        self.line_3.setGeometry(QtCore.QRect(10, 260, 280, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        self.line_3.setPalette(palette)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.grp_device = QtWidgets.QGroupBox(self.frame)
        self.grp_device.setGeometry(QtCore.QRect(10, 360, 291, 101))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.grp_device.setPalette(palette)
        self.grp_device.setObjectName("grp_device")
        self.lbl_device_id = QtWidgets.QLabel(self.grp_device)
        self.lbl_device_id.setGeometry(QtCore.QRect(10, 20, 271, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lbl_device_id.setPalette(palette)
        self.lbl_device_id.setObjectName("lbl_device_id")
        self.lbl_device_description = QtWidgets.QLabel(self.grp_device)
        self.lbl_device_description.setGeometry(QtCore.QRect(10, 40, 271, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lbl_device_description.setPalette(palette)
        self.lbl_device_description.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lbl_device_description.setWordWrap(True)
        self.lbl_device_description.setObjectName("lbl_device_description")
        self.frame_2.raise_()
        self.lbl_event_id.raise_()
        self.lbl_user.raise_()
        self.lbl_user_data.raise_()
        self.lbl_created.raise_()
        self.lbl_created_data.raise_()
        self.lbl_wallet_data.raise_()
        self.lbl_wallet.raise_()
        self.lbl_app.raise_()
        self.line_2.raise_()
        self.line_3.raise_()
        self.grp_device.raise_()
        self.txt_income_rsd = QtWidgets.QLineEdit(Dialog)
        self.txt_income_rsd.setGeometry(QtCore.QRect(460, 110, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txt_income_rsd.setFont(font)
        self.txt_income_rsd.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txt_income_rsd.setObjectName("txt_income_rsd")
        self.txt_outcome_rsd = QtWidgets.QLineEdit(Dialog)
        self.txt_outcome_rsd.setGeometry(QtCore.QRect(460, 150, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txt_outcome_rsd.setFont(font)
        self.txt_outcome_rsd.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txt_outcome_rsd.setObjectName("txt_outcome_rsd")
        self.lbl_income_rsd = QtWidgets.QLabel(Dialog)
        self.lbl_income_rsd.setGeometry(QtCore.QRect(310, 110, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_income_rsd.setFont(font)
        self.lbl_income_rsd.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_income_rsd.setObjectName("lbl_income_rsd")
        self.lbl_outcome_rsd = QtWidgets.QLabel(Dialog)
        self.lbl_outcome_rsd.setGeometry(QtCore.QRect(310, 150, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_outcome_rsd.setFont(font)
        self.lbl_outcome_rsd.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_outcome_rsd.setObjectName("lbl_outcome_rsd")
        self.lbl_outcome_eur = QtWidgets.QLabel(Dialog)
        self.lbl_outcome_eur.setGeometry(QtCore.QRect(310, 230, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_outcome_eur.setFont(font)
        self.lbl_outcome_eur.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_outcome_eur.setObjectName("lbl_outcome_eur")
        self.txt_income_eur = QtWidgets.QLineEdit(Dialog)
        self.txt_income_eur.setGeometry(QtCore.QRect(460, 190, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txt_income_eur.setFont(font)
        self.txt_income_eur.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txt_income_eur.setObjectName("txt_income_eur")
        self.txt_outcome_eur = QtWidgets.QLineEdit(Dialog)
        self.txt_outcome_eur.setGeometry(QtCore.QRect(460, 230, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txt_outcome_eur.setFont(font)
        self.txt_outcome_eur.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txt_outcome_eur.setObjectName("txt_outcome_eur")
        self.lbl_income_eur = QtWidgets.QLabel(Dialog)
        self.lbl_income_eur.setGeometry(QtCore.QRect(310, 190, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_income_eur.setFont(font)
        self.lbl_income_eur.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_income_eur.setObjectName("lbl_income_eur")
        self.lbl_place = QtWidgets.QLabel(Dialog)
        self.lbl_place.setGeometry(QtCore.QRect(600, 170, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_place.setFont(font)
        self.lbl_place.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_place.setObjectName("lbl_place")
        self.lbl_event_type = QtWidgets.QLabel(Dialog)
        self.lbl_event_type.setGeometry(QtCore.QRect(600, 110, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_event_type.setFont(font)
        self.lbl_event_type.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_event_type.setObjectName("lbl_event_type")
        self.cmb_place = QtWidgets.QComboBox(Dialog)
        self.cmb_place.setGeometry(QtCore.QRect(740, 170, 201, 31))
        self.cmb_place.setObjectName("cmb_place")
        self.cmb_event_type = QtWidgets.QComboBox(Dialog)
        self.cmb_event_type.setGeometry(QtCore.QRect(740, 110, 201, 31))
        self.cmb_event_type.setObjectName("cmb_event_type")
        self.btn_new_event_type = QtWidgets.QPushButton(Dialog)
        self.btn_new_event_type.setGeometry(QtCore.QRect(880, 140, 61, 21))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("data/assets/new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_new_event_type.setIcon(icon1)
        self.btn_new_event_type.setIconSize(QtCore.QSize(20, 18))
        self.btn_new_event_type.setObjectName("btn_new_event_type")
        self.btn_new_place = QtWidgets.QPushButton(Dialog)
        self.btn_new_place.setGeometry(QtCore.QRect(880, 200, 61, 21))
        self.btn_new_place.setIcon(icon1)
        self.btn_new_place.setIconSize(QtCore.QSize(20, 18))
        self.btn_new_place.setObjectName("btn_new_place")
        self.lbl_partner = QtWidgets.QLabel(Dialog)
        self.lbl_partner.setGeometry(QtCore.QRect(580, 230, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_partner.setFont(font)
        self.lbl_partner.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_partner.setObjectName("lbl_partner")
        self.cmb_partner = QtWidgets.QComboBox(Dialog)
        self.cmb_partner.setGeometry(QtCore.QRect(720, 230, 221, 31))
        self.cmb_partner.setEditable(True)
        self.cmb_partner.setObjectName("cmb_partner")
        self.txt_description = QtWidgets.QLineEdit(Dialog)
        self.txt_description.setGeometry(QtCore.QRect(460, 340, 481, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txt_description.setFont(font)
        self.txt_description.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.txt_description.setClearButtonEnabled(False)
        self.txt_description.setObjectName("txt_description")
        self.lbl_description = QtWidgets.QLabel(Dialog)
        self.lbl_description.setGeometry(QtCore.QRect(350, 340, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_description.setFont(font)
        self.lbl_description.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_description.setObjectName("lbl_description")
        self.lbl_date = QtWidgets.QLabel(Dialog)
        self.lbl_date.setGeometry(QtCore.QRect(420, 40, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_date.setFont(font)
        self.lbl_date.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_date.setObjectName("lbl_date")
        self.dt_date = QtWidgets.QDateEdit(Dialog)
        self.dt_date.setGeometry(QtCore.QRect(530, 40, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.dt_date.setFont(font)
        self.dt_date.setObjectName("dt_date")
        self.btn_date_pick = QtWidgets.QPushButton(Dialog)
        self.btn_date_pick.setGeometry(QtCore.QRect(680, 40, 71, 31))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("data/assets/calendar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_date_pick.setIcon(icon2)
        self.btn_date_pick.setIconSize(QtCore.QSize(22, 18))
        self.btn_date_pick.setObjectName("btn_date_pick")
        self.lbl_exchange = QtWidgets.QLabel(Dialog)
        self.lbl_exchange.setGeometry(QtCore.QRect(320, 260, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_exchange.setFont(font)
        self.lbl_exchange.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_exchange.setWordWrap(True)
        self.lbl_exchange.setObjectName("lbl_exchange")
        self.txt_exchange = QtWidgets.QLineEdit(Dialog)
        self.txt_exchange.setGeometry(QtCore.QRect(460, 270, 111, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.txt_exchange.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txt_exchange.setFont(font)
        self.txt_exchange.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txt_exchange.setObjectName("txt_exchange")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(320, 440, 631, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_4 = QtWidgets.QFrame(Dialog)
        self.line_4.setGeometry(QtCore.QRect(320, 80, 631, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.btn_cancel = QtWidgets.QPushButton(Dialog)
        self.btn_cancel.setGeometry(QtCore.QRect(850, 460, 101, 31))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("data/assets/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_cancel.setIcon(icon3)
        self.btn_cancel.setObjectName("btn_cancel")
        self.btn_save = QtWidgets.QPushButton(Dialog)
        self.btn_save.setGeometry(QtCore.QRect(740, 460, 101, 31))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("data/assets/ok.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_save.setIcon(icon4)
        self.btn_save.setObjectName("btn_save")
        self.lbl_view_counterpart = QtWidgets.QLabel(Dialog)
        self.lbl_view_counterpart.setGeometry(QtCore.QRect(720, 230, 221, 101))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.lbl_view_counterpart.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl_view_counterpart.setFont(font)
        self.lbl_view_counterpart.setAutoFillBackground(True)
        self.lbl_view_counterpart.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_view_counterpart.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lbl_view_counterpart.setScaledContents(False)
        self.lbl_view_counterpart.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lbl_view_counterpart.setWordWrap(True)
        self.lbl_view_counterpart.setObjectName("lbl_view_counterpart")
        self.lbl_view_description = QtWidgets.QLabel(Dialog)
        self.lbl_view_description.setGeometry(QtCore.QRect(460, 340, 481, 101))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.lbl_view_description.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl_view_description.setFont(font)
        self.lbl_view_description.setAutoFillBackground(True)
        self.lbl_view_description.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_view_description.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lbl_view_description.setScaledContents(False)
        self.lbl_view_description.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lbl_view_description.setWordWrap(True)
        self.lbl_view_description.setObjectName("lbl_view_description")
        self.btn_left = QtWidgets.QPushButton(Dialog)
        self.btn_left.setGeometry(QtCore.QRect(880, 20, 31, 41))
        self.btn_left.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("data/assets/arrow_move_left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_left.setIcon(icon5)
        self.btn_left.setIconSize(QtCore.QSize(50, 50))
        self.btn_left.setFlat(True)
        self.btn_left.setObjectName("btn_left")
        self.btn_right = QtWidgets.QPushButton(Dialog)
        self.btn_right.setGeometry(QtCore.QRect(920, 20, 31, 41))
        self.btn_right.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("data/assets/arrow_move_right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_right.setIcon(icon6)
        self.btn_right.setIconSize(QtCore.QSize(50, 50))
        self.btn_right.setFlat(True)
        self.btn_right.setObjectName("btn_right")
        self.lbl_event_position = QtWidgets.QLabel(Dialog)
        self.lbl_event_position.setGeometry(QtCore.QRect(760, 60, 181, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(86, 65, 2))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(86, 65, 2))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lbl_event_position.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_event_position.setFont(font)
        self.lbl_event_position.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_event_position.setObjectName("lbl_event_position")

        QtCore.QMetaObject.connectSlotsByName(Dialog)
