from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import connection
import log_cls


class Ui_Dialog:
    """Login Window. Selecting user."""

    def __init__(self):
        self.log = log_cls.LogData()

    def setupUi(self, Dialog, app):
        self.dialog = Dialog
        Dialog.setObjectName("Dialog")
        Dialog.setFixedSize(696, 326)
        
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(162, 209, 209))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(162, 209, 209))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(162, 209, 209))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(162, 209, 209))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        Dialog.setPalette(palette)
        Dialog.setAutoFillBackground(True)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 321, 311))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("data\\assets\\matrix_small.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.lbl_info_caption = QtWidgets.QLabel(Dialog)
        self.lbl_info_caption.setGeometry(QtCore.QRect(40, 20, 231, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lbl_info_caption.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(26)
        self.lbl_info_caption.setFont(font)
        self.lbl_info_caption.setObjectName("lbl_info_caption")
        self.lbl_info_desc = QtWidgets.QLabel(Dialog)
        self.lbl_info_desc.setGeometry(QtCore.QRect(40, 90, 261, 111))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lbl_info_desc.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        self.lbl_info_desc.setFont(font)
        self.lbl_info_desc.setWordWrap(True)
        self.lbl_info_desc.setObjectName("lbl_info_desc")
        self.lbl_info_new_user = QtWidgets.QLabel(Dialog)
        self.lbl_info_new_user.setGeometry(QtCore.QRect(40, 210, 151, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lbl_info_new_user.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        self.lbl_info_new_user.setFont(font)
        self.lbl_info_new_user.setWordWrap(True)
        self.lbl_info_new_user.setObjectName("lbl_info_new_user")
        self.lbl_info_new_user_desc = QtWidgets.QLabel(Dialog)
        self.lbl_info_new_user_desc.setGeometry(QtCore.QRect(40, 250, 271, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lbl_info_new_user_desc.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        self.lbl_info_new_user_desc.setFont(font)
        self.lbl_info_new_user_desc.setWordWrap(True)
        self.lbl_info_new_user_desc.setObjectName("lbl_info_new_user_desc")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(400, 0, 211, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_6.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.cmb_user = QtWidgets.QComboBox(Dialog)
        self.cmb_user.setGeometry(QtCore.QRect(440, 30, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cmb_user.setFont(font)
        self.cmb_user.setObjectName("cmb_user")
        self.txt_password = QtWidgets.QLineEdit(Dialog)
        self.txt_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txt_password.setGeometry(QtCore.QRect(440, 90, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txt_password.setFont(font)
        self.txt_password.setObjectName("txt_password")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(400, 60, 211, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_7.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.btn_new_user = QtWidgets.QPushButton(Dialog, clicked = self.btn_new_user_click)
        self.btn_new_user.setGeometry(QtCore.QRect(590, 130, 93, 28))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("data\\assets\\user_add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_new_user.setIcon(icon)
        self.btn_new_user.setObjectName("btn_new_user")
        self.btn_login = QtWidgets.QPushButton(Dialog)
        self.btn_login.clicked.connect(self.btn_login_click)
        self.btn_login.setGeometry(QtCore.QRect(490, 290, 93, 28))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("data\\assets\\ok.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_login.setIcon(icon1)
        self.btn_login.setObjectName("btn_login")
        self.btn_exit = QtWidgets.QPushButton(Dialog, clicked = self.btn_exit_click)
        self.btn_exit.setGeometry(QtCore.QRect(590, 290, 93, 28))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("data\\assets\\close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_exit.setIcon(icon2)
        self.btn_exit.setObjectName("btn_exit")
        self.lbl_name = QtWidgets.QLabel(Dialog)
        self.lbl_name.setGeometry(QtCore.QRect(400, 180, 281, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.lbl_name.setFont(font)
        self.lbl_name.setObjectName("lbl_name")
        self.lbl_adress = QtWidgets.QLabel(Dialog)
        self.lbl_adress.setGeometry(QtCore.QRect(400, 210, 281, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.lbl_adress.setFont(font)
        self.lbl_adress.setWordWrap(True)
        self.lbl_adress.setObjectName("lbl_adress")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(400, 170, 281, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setGeometry(QtCore.QRect(400, 270, 281, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(400, 30, 31, 31))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("data\\assets\\user.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(400, 90, 31, 31))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("data\\assets\\user_password.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.frm_new_user = QtWidgets.QFrame(Dialog)
        self.frm_new_user.setGeometry(QtCore.QRect(390, 5, 295, 316))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.frm_new_user.setPalette(palette)
        self.frm_new_user.setAutoFillBackground(True)
        self.frm_new_user.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_new_user.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_new_user.setObjectName("frm_new_user")
        self.txt_new_username = QtWidgets.QLineEdit(self.frm_new_user)
        self.txt_new_username.textChanged.connect(self.txt_new_username_changed)
        self.txt_new_username.setGeometry(QtCore.QRect(20, 60, 241, 22))
        self.txt_new_username.setObjectName("txt_new_username")
        self.lbl_new_username = QtWidgets.QLabel(self.frm_new_user)
        self.lbl_new_username.setGeometry(QtCore.QRect(20, 30, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_new_username.setFont(font)
        self.lbl_new_username.setObjectName("lbl_new_username")
        self.txt_new_password = QtWidgets.QLineEdit(self.frm_new_user)
        self.txt_new_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txt_new_password.setGeometry(QtCore.QRect(20, 120, 241, 22))
        self.txt_new_password.setObjectName("txt_new_password")
        self.lbl_new_password = QtWidgets.QLabel(self.frm_new_user)
        self.lbl_new_password.setGeometry(QtCore.QRect(20, 90, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_new_password.setFont(font)
        self.lbl_new_password.setObjectName("lbl_new_password")
        self.txt_new_password_confirm = QtWidgets.QLineEdit(self.frm_new_user)
        self.txt_new_password_confirm.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txt_new_password_confirm.setGeometry(QtCore.QRect(20, 180, 241, 22))
        self.txt_new_password_confirm.setObjectName("txt_new_password_confirm")
        self.lbl_new_password_confirm = QtWidgets.QLabel(self.frm_new_user)
        self.lbl_new_password_confirm.setGeometry(QtCore.QRect(20, 150, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_new_password_confirm.setFont(font)
        self.lbl_new_password_confirm.setObjectName("lbl_new_password_confirm")
        self.btn_new_ok = QtWidgets.QPushButton(self.frm_new_user, clicked = self.btn_new_ok_click)
        self.btn_new_ok.setGeometry(QtCore.QRect(80, 270, 93, 28))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("data\\assets\\ok.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_new_ok.setIcon(icon3)
        self.btn_new_ok.setObjectName("btn_new_ok")
        self.btn_new_cancel = QtWidgets.QPushButton(self.frm_new_user, clicked = self.btn_new_cancel_click)
        self.btn_new_cancel.setGeometry(QtCore.QRect(180, 270, 93, 28))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("data\\assets\\close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_new_cancel.setIcon(icon4)
        self.btn_new_cancel.setObjectName("btn_new_cancel")
        self.lbl_new_warning = QtWidgets.QLabel(self.frm_new_user)
        self.lbl_new_warning.setGeometry(QtCore.QRect(20, 220, 251, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lbl_new_warning.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_new_warning.setFont(font)
        self.lbl_new_warning.setWordWrap(True)
        self.lbl_new_warning.setObjectName("lbl_new_warning")

        # self.retranslateUi(Dialog)
        self.start_setup(Dialog)  # Set values for login window
        self.cmb_user.currentIndexChanged.connect(self.cmb_user_changed)
        self.txt_password.setFocus()
        self.txt_password.returnPressed.connect(self.btn_login_click)
                

        QtCore.QMetaObject.connectSlotsByName(Dialog)
        # Dialog.setTabOrder(self.btn_login, self.btn_exit)
        Dialog.setTabOrder(self.cmb_user, self.txt_password)
        Dialog.setTabOrder(self.txt_password, self.cmb_user)
        Dialog.setTabOrder(self.btn_exit, self.btn_new_user)
        Dialog.setTabOrder(self.btn_new_user, self.txt_new_username)
        Dialog.setTabOrder(self.txt_new_username, self.txt_new_password)
        Dialog.setTabOrder(self.txt_new_password, self.txt_new_password_confirm)
        Dialog.setTabOrder(self.txt_new_password_confirm, self.btn_new_ok)
        Dialog.setTabOrder(self.btn_new_ok, self.btn_new_cancel)
        
        self.selected_user = []
        Dialog.show()
        app.exec_()
        
        if len(self.selected_user) == 0:
            return ""
        else:
            self.conn.set_last_user(self.selected_user[0][1])
            return self.selected_user[0][0]

    def retranslateUi(self, lang):
        self.lbl_info_caption.setText(self.conn.lang("login_lbl_info_caption", lang))
        self.lbl_info_desc.setText(self.conn.lang("login_lbl_info_desc", lang))
        self.lbl_info_new_user.setText(self.conn.lang("login_lbl_info_new_user", lang))
        self.lbl_info_new_user_desc.setText(self.conn.lang("login_lbl_info_new_user_desc", lang))
        self.label_6.setText(self.conn.lang("login_label_6", lang))
        self.label_7.setText(self.conn.lang("login_label_7", lang))
        self.btn_new_user.setText(self.conn.lang("login_btn_new_user", lang))
        self.btn_login.setText(self.conn.lang("login_btn_login", lang))
        self.btn_exit.setText(self.conn.lang("btn_exit", lang))
        self.lbl_new_username.setText(self.conn.lang("login_lbl_new_username", lang))
        self.lbl_new_password.setText(self.conn.lang("login_lbl_new_password", lang))
        self.lbl_new_password_confirm.setText(self.conn.lang("login_lbl_new_password_confirm", lang))
        self.btn_new_ok.setText(self.conn.lang("btn_ok", lang))
        self.btn_new_cancel.setText(self.conn.lang("btn_cancel", lang))

    def btn_exit_click(self):
        self.dialog.close()

    def btn_login_click(self):
        pass_check = self.conn.check_user_password(self.cmb_user.currentData(), self.txt_password.text())
        if pass_check:
            self.selected_user.append([self.cmb_user.currentText(), self.cmb_user.currentData()])
            self.dialog.close()
        else:
            self.log.write_log(f"Warning. Attempt to login, incorect password, user: {self.cmb_user.currentText()}")
            lang = self.conn.user_language(0,self.cmb_user.currentText())
            msg_text = self.conn.lang("msg_login_wrong_password", lang)
            msg_title = self.conn.lang("msg_login_wrong_password_title", lang)
            self.txt_password.setText("")
            self.txt_password.setPlaceholderText(msg_title)
            # result = QMessageBox.warning(None, msg_title, msg_text, QMessageBox.Ok)
            

    def cmb_user_changed(self):
        # Sets dialog language to seleected user and updates user info.
        self.txt_password.setText("")
        if self.cmb_user.currentText() != "":
            lang = self.conn.user_language(0,self.cmb_user.currentText())
            self.retranslateUi(lang)
            self.update_user_info()
            
    def update_user_info(self):
        if self.cmb_user.currentData() is None:
            self.lbl_name.setText("")
            self.lbl_adress.setText("")
            return
        cr_data = int(self.cmb_user.currentData())
        for i in self.users_list:
            if i[0] == cr_data:
                self.lbl_name.setText(f"{i[5]} {i[4]}")
                self.lbl_adress.setText(i[7])

    def start_setup(self, Dialog):
        self.frm_new_user.setVisible(False)
        self.conn = connection.ConnStart()
        self.users_list = self.conn.get_users_all()
        for i in self.users_list:  # Adds all users to ComboBox.
            self.cmb_user.addItem(i[1], i[0])
        # self.lbl_name.setText("")
        # self.lbl_adress.setText("")
        self.lbl_new_warning.setText("")
        lang = self.conn.user_language(self.conn.get_setting_data("last_user", getParametar=True))
        Dialog.setWindowTitle(self.conn.lang("login_caption", lang))

        self.retranslateUi(lang)

        self.cmb_user.setCurrentText(self.conn.get_setting_data("last_user"))
        self.update_user_info()

    def btn_new_ok_click(self):
        is_valid = self.conn.is_valid_username(self.txt_new_username.text())
        # Check if name contains illegal characters.
        if is_valid[0][0] is False:
            self.lbl_new_warning.setText(is_valid[0][1])
            return
        # Check password and confirm password match.
        if self.txt_new_password.text() != self.txt_new_password_confirm.text():
            self.lbl_new_warning.setText(self.conn.lang("login_lbl_new_warning3"))
            return
        # Check username already exists.
        if self.conn._get_user_id(self.txt_new_username.text()) != "":
            self.lbl_new_warning.setText(self.conn.lang("login_lbl_new_warning4"))
            return
        if len(self.txt_new_password.text()) > 30:
            self.lbl_new_warning.setText(self.conn.lang("login_lbl_new_warning5"))
            return
        
        a = self.conn.add_new_user(self.txt_new_username.text(), self.txt_new_password.text())
        if a == False:
            return
        self.cmb_user.addItem(self.txt_new_username.text(), self.conn._get_user_id(self.txt_new_username.text()))
        self.cmb_user.setCurrentText(self.txt_new_username.text())
        self.txt_new_username.setText("")
        self.txt_new_password.setText("")
        self.txt_new_password_confirm.setText("")
        self.lbl_new_warning.setText("")
        self.frm_new_user.setVisible(False)
        self.users_list = self.conn.get_users_all()
        self.lbl_name.setText("")
        self.lbl_adress.setText("")

    def txt_new_username_changed(self):
        self.lbl_new_warning.setText("")

    def btn_new_cancel_click(self):
        self.lbl_new_warning.setText("")
        self.frm_new_user.setVisible(False)

    def btn_new_user_click(self):
        self.frm_new_user.setVisible(True)

