from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.WindowModal)
        Dialog.resize(725, 406)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        Dialog.setPalette(palette)
        Dialog.setModal(True)
        self.lbl_caption = QtWidgets.QLabel(Dialog)
        self.lbl_caption.setGeometry(QtCore.QRect(0, 0, 621, 81))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lbl_caption.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lbl_caption.setFont(font)
        self.lbl_caption.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_caption.setObjectName("lbl_caption")
        self.lbl_surname = QtWidgets.QLabel(Dialog)
        self.lbl_surname.setGeometry(QtCore.QRect(10, 140, 91, 21))
        self.lbl_surname.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_surname.setObjectName("lbl_surname")
        self.txt_forename = QtWidgets.QLineEdit(Dialog)
        self.txt_forename.setGeometry(QtCore.QRect(110, 110, 291, 22))
        self.txt_forename.setObjectName("txt_forename")
        self.lbl_forename = QtWidgets.QLabel(Dialog)
        self.lbl_forename.setGeometry(QtCore.QRect(10, 110, 91, 21))
        self.lbl_forename.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_forename.setObjectName("lbl_forename")
        self.txt_surname = QtWidgets.QLineEdit(Dialog)
        self.txt_surname.setGeometry(QtCore.QRect(110, 140, 291, 22))
        self.txt_surname.setObjectName("txt_surname")
        self.lbl_address = QtWidgets.QLabel(Dialog)
        self.lbl_address.setGeometry(QtCore.QRect(10, 170, 91, 21))
        self.lbl_address.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_address.setObjectName("lbl_address")
        self.lbl_mail = QtWidgets.QLabel(Dialog)
        self.lbl_mail.setGeometry(QtCore.QRect(10, 230, 91, 21))
        self.lbl_mail.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_mail.setObjectName("lbl_mail")
        self.txt_mail = QtWidgets.QLineEdit(Dialog)
        self.txt_mail.setGeometry(QtCore.QRect(110, 230, 291, 22))
        self.txt_mail.setObjectName("txt_mail")
        self.txt_phone = QtWidgets.QLineEdit(Dialog)
        self.txt_phone.setGeometry(QtCore.QRect(110, 260, 291, 22))
        self.txt_phone.setObjectName("txt_phone")
        self.lbl_phone = QtWidgets.QLabel(Dialog)
        self.lbl_phone.setGeometry(QtCore.QRect(10, 260, 91, 21))
        self.lbl_phone.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_phone.setObjectName("lbl_phone")
        self.lbl_description = QtWidgets.QLabel(Dialog)
        self.lbl_description.setGeometry(QtCore.QRect(10, 290, 91, 21))
        self.lbl_description.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_description.setObjectName("lbl_description")
        self.txt_description = QtWidgets.QTextEdit(Dialog)
        self.txt_description.setGeometry(QtCore.QRect(110, 290, 601, 51))
        self.txt_description.setObjectName("txt_description")
        self.btn_change_password = QtWidgets.QPushButton(Dialog)
        self.btn_change_password.setGeometry(QtCore.QRect(440, 110, 271, 28))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("data/assets/user_password.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_change_password.setIcon(icon)
        self.btn_change_password.setAutoDefault(False)
        self.btn_change_password.setObjectName("btn_change_password")
        self.cmb_lang = QtWidgets.QComboBox(Dialog)
        self.cmb_lang.setGeometry(QtCore.QRect(440, 170, 271, 31))
        self.cmb_lang.setObjectName("cmb_lang")
        self.lbl_lang = QtWidgets.QLabel(Dialog)
        self.lbl_lang.setGeometry(QtCore.QRect(440, 150, 271, 21))
        self.lbl_lang.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_lang.setObjectName("lbl_lang")
        self.btn_change_database = QtWidgets.QPushButton(Dialog)
        self.btn_change_database.setGeometry(QtCore.QRect(440, 220, 271, 28))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("data/assets/tree_view.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_change_database.setIcon(icon1)
        self.btn_change_database.setAutoDefault(False)
        self.btn_change_database.setObjectName("btn_change_database")
        self.btn_cancel = QtWidgets.QPushButton(Dialog)
        self.btn_cancel.setGeometry(QtCore.QRect(620, 360, 93, 28))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("data/assets/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_cancel.setIcon(icon2)
        self.btn_cancel.setAutoDefault(False)
        self.btn_cancel.setObjectName("btn_cancel")
        self.btn_confirm = QtWidgets.QPushButton(Dialog)
        self.btn_confirm.setGeometry(QtCore.QRect(520, 360, 93, 28))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("data/assets/ok.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_confirm.setIcon(icon3)
        self.btn_confirm.setAutoDefault(False)
        self.btn_confirm.setObjectName("btn_confirm")
        self.txt_address = QtWidgets.QTextEdit(Dialog)
        self.txt_address.setGeometry(QtCore.QRect(110, 170, 291, 51))
        self.txt_address.setObjectName("txt_address")

        QtCore.QMetaObject.connectSlotsByName(Dialog)
