from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.WindowModal)
        Dialog.resize(480, 180)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        Dialog.setPalette(palette)
        Dialog.setModal(True)
        self.lbl_old_password = QtWidgets.QLabel(Dialog)
        self.lbl_old_password.setGeometry(QtCore.QRect(20, 20, 411, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_old_password.setFont(font)
        self.lbl_old_password.setObjectName("lbl_old_password")
        self.btn_confirm = QtWidgets.QPushButton(Dialog)
        self.btn_confirm.setGeometry(QtCore.QRect(270, 140, 93, 28))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("data/assets/ok.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_confirm.setIcon(icon)
        self.btn_confirm.setAutoDefault(False)
        self.btn_confirm.setObjectName("btn_confirm")
        self.btn_cancel = QtWidgets.QPushButton(Dialog)
        self.btn_cancel.setGeometry(QtCore.QRect(370, 140, 93, 28))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("data/assets/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_cancel.setIcon(icon1)
        self.btn_cancel.setAutoDefault(False)
        self.btn_cancel.setObjectName("btn_cancel")
        self.txt_password = QtWidgets.QLineEdit(Dialog)
        self.txt_password.setGeometry(QtCore.QRect(40, 60, 391, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txt_password.setFont(font)
        self.txt_password.setText("")
        self.txt_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txt_password.setClearButtonEnabled(False)
        self.txt_password.setObjectName("txt_password")
        self.btn_show_password = QtWidgets.QPushButton(Dialog)
        self.btn_show_password.setGeometry(QtCore.QRect(430, 60, 31, 31))
        self.btn_show_password.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("data/assets/show_all.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_show_password.setIcon(icon2)
        self.btn_show_password.setAutoDefault(False)
        self.btn_show_password.setObjectName("btn_show_password")
        self.btn_next = QtWidgets.QPushButton(Dialog)
        self.btn_next.setGeometry(QtCore.QRect(270, 140, 93, 28))
        self.btn_next.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("data/assets/arrow_move_right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_next.setIcon(icon3)
        self.btn_next.setAutoDefault(False)
        self.btn_next.setObjectName("btn_next")
        self.frm_confirm = QtWidgets.QFrame(Dialog)
        self.frm_confirm.setGeometry(QtCore.QRect(0, 0, 481, 131))
        self.frm_confirm.setAutoFillBackground(True)
        self.frm_confirm.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frm_confirm.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frm_confirm.setObjectName("frm_confirm")
        self.lbl_new_password = QtWidgets.QLabel(self.frm_confirm)
        self.lbl_new_password.setGeometry(QtCore.QRect(10, 30, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_new_password.setFont(font)
        self.lbl_new_password.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_new_password.setObjectName("lbl_new_password")
        self.txt_new_password = QtWidgets.QLineEdit(self.frm_confirm)
        self.txt_new_password.setGeometry(QtCore.QRect(170, 30, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txt_new_password.setFont(font)
        self.txt_new_password.setText("")
        self.txt_new_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txt_new_password.setClearButtonEnabled(False)
        self.txt_new_password.setObjectName("txt_new_password")
        self.btn_show_password_2 = QtWidgets.QPushButton(self.frm_confirm)
        self.btn_show_password_2.setGeometry(QtCore.QRect(440, 30, 31, 31))
        self.btn_show_password_2.setText("")
        self.btn_show_password_2.setIcon(icon2)
        self.btn_show_password_2.setAutoDefault(False)
        self.btn_show_password_2.setObjectName("btn_show_password_2")
        self.btn_show_password_3 = QtWidgets.QPushButton(self.frm_confirm)
        self.btn_show_password_3.setGeometry(QtCore.QRect(440, 70, 31, 31))
        self.btn_show_password_3.setText("")
        self.btn_show_password_3.setIcon(icon2)
        self.btn_show_password_3.setAutoDefault(False)
        self.btn_show_password_3.setObjectName("btn_show_password_3")
        self.txt_confirm_password = QtWidgets.QLineEdit(self.frm_confirm)
        self.txt_confirm_password.setGeometry(QtCore.QRect(170, 70, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txt_confirm_password.setFont(font)
        self.txt_confirm_password.setText("")
        self.txt_confirm_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txt_confirm_password.setClearButtonEnabled(False)
        self.txt_confirm_password.setObjectName("txt_confirm_password")
        self.lbl_confirm_password = QtWidgets.QLabel(self.frm_confirm)
        self.lbl_confirm_password.setGeometry(QtCore.QRect(10, 70, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_confirm_password.setFont(font)
        self.lbl_confirm_password.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_confirm_password.setObjectName("lbl_confirm_password")
        self.btn_back = QtWidgets.QPushButton(Dialog)
        self.btn_back.setGeometry(QtCore.QRect(170, 140, 93, 28))
        self.btn_back.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("data/assets/arrow_move_left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_back.setIcon(icon4)
        self.btn_back.setAutoDefault(False)
        self.btn_back.setObjectName("btn_back")
        self.frm_finish = QtWidgets.QFrame(Dialog)
        self.frm_finish.setGeometry(QtCore.QRect(0, 0, 481, 130))
        self.frm_finish.setAutoFillBackground(True)
        self.frm_finish.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frm_finish.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frm_finish.setObjectName("frm_finish")
        self.lbl_password_info1 = QtWidgets.QLabel(self.frm_finish)
        self.lbl_password_info1.setGeometry(QtCore.QRect(10, 30, 461, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_password_info1.setFont(font)
        self.lbl_password_info1.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_password_info1.setObjectName("lbl_password_info1")
        self.lbl_password_info2 = QtWidgets.QLabel(self.frm_finish)
        self.lbl_password_info2.setGeometry(QtCore.QRect(10, 70, 461, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_password_info2.setFont(font)
        self.lbl_password_info2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_password_info2.setObjectName("lbl_password_info2")

        QtCore.QMetaObject.connectSlotsByName(Dialog)
