from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1044, 453)
        self.tbl_walets = QtWidgets.QTableWidget(Dialog)
        self.tbl_walets.setGeometry(QtCore.QRect(0, 60, 250, 391))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.tbl_walets.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tbl_walets.setFont(font)
        self.tbl_walets.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.tbl_walets.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tbl_walets.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tbl_walets.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tbl_walets.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tbl_walets.setObjectName("tbl_walets")
        self.tbl_walets.setColumnCount(0)
        self.tbl_walets.setRowCount(0)
        self.tbl_walets.verticalHeader().setVisible(False)
        self.tbl_walets.verticalHeader().setDefaultSectionSize(50)
        self.lbl_caption = QtWidgets.QLabel(Dialog)
        self.lbl_caption.setGeometry(QtCore.QRect(0, 0, 1031, 60))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.lbl_caption.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.lbl_caption.setFont(font)
        self.lbl_caption.setAutoFillBackground(True)
        self.lbl_caption.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_caption.setObjectName("lbl_caption")
        self.tbl_events = QtWidgets.QTableWidget(Dialog)
        self.tbl_events.setGeometry(QtCore.QRect(250, 210, 781, 201))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tbl_events.setFont(font)
        self.tbl_events.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.tbl_events.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tbl_events.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tbl_events.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tbl_events.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tbl_events.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.tbl_events.setObjectName("tbl_events")
        self.tbl_events.setColumnCount(0)
        self.tbl_events.setRowCount(0)
        self.tbl_events.verticalHeader().setDefaultSectionSize(50)
        self.frm_options = QtWidgets.QFrame(Dialog)
        self.frm_options.setGeometry(QtCore.QRect(250, 60, 771, 111))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.frm_options.setPalette(palette)
        self.frm_options.setAutoFillBackground(True)
        self.frm_options.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_options.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_options.setObjectName("frm_options")
        self.lbl_info_wallet = QtWidgets.QLabel(self.frm_options)
        self.lbl_info_wallet.setGeometry(QtCore.QRect(0, 0, 771, 30))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lbl_info_wallet.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_info_wallet.setFont(font)
        self.lbl_info_wallet.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_info_wallet.setObjectName("lbl_info_wallet")
        self.lbl_info_description = QtWidgets.QLabel(self.frm_options)
        self.lbl_info_description.setGeometry(QtCore.QRect(10, 40, 261, 61))
        self.lbl_info_description.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lbl_info_description.setWordWrap(True)
        self.lbl_info_description.setObjectName("lbl_info_description")
        self.btn_add_new = QtWidgets.QPushButton(self.frm_options)
        self.btn_add_new.setGeometry(QtCore.QRect(360, 70, 131, 28))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("data/assets/main_bank.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_add_new.setIcon(icon)
        self.btn_add_new.setAutoDefault(False)
        self.btn_add_new.setObjectName("btn_add_new")
        self.btn_transfer = QtWidgets.QPushButton(self.frm_options)
        self.btn_transfer.setGeometry(QtCore.QRect(500, 70, 191, 28))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("data/assets/transfer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_transfer.setIcon(icon1)
        self.btn_transfer.setAutoDefault(False)
        self.btn_transfer.setObjectName("btn_transfer")
        self.btn_delete = QtWidgets.QPushButton(self.frm_options)
        self.btn_delete.setGeometry(QtCore.QRect(360, 40, 131, 28))
        self.btn_delete.setIcon(icon)
        self.btn_delete.setAutoDefault(False)
        self.btn_delete.setObjectName("btn_delete")
        self.frm_details_2 = QtWidgets.QFrame(Dialog)
        self.frm_details_2.setGeometry(QtCore.QRect(250, 410, 791, 40))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(145, 195, 195))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(145, 195, 195))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(145, 195, 195))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(145, 195, 195))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.frm_details_2.setPalette(palette)
        self.frm_details_2.setAutoFillBackground(True)
        self.frm_details_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_details_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_details_2.setObjectName("frm_details_2")
        self.lbl_total_income = QtWidgets.QLabel(self.frm_details_2)
        self.lbl_total_income.setGeometry(QtCore.QRect(140, 0, 140, 40))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lbl_total_income.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_total_income.setFont(font)
        self.lbl_total_income.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_total_income.setObjectName("lbl_total_income")
        self.lbl_total_outcome = QtWidgets.QLabel(self.frm_details_2)
        self.lbl_total_outcome.setGeometry(QtCore.QRect(450, 0, 140, 40))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lbl_total_outcome.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_total_outcome.setFont(font)
        self.lbl_total_outcome.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_total_outcome.setObjectName("lbl_total_outcome")
        self.btn_total = QtWidgets.QPushButton(self.frm_details_2)
        self.btn_total.setGeometry(QtCore.QRect(5, 2, 131, 36))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_total.setFont(font)
        self.btn_total.setAutoDefault(False)
        self.btn_total.setObjectName("btn_total")
        self.lbl_total_income_data = QtWidgets.QLabel(self.frm_details_2)
        self.lbl_total_income_data.setGeometry(QtCore.QRect(280, 0, 160, 40))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lbl_total_income_data.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_total_income_data.setFont(font)
        self.lbl_total_income_data.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_total_income_data.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lbl_total_income_data.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_total_income_data.setObjectName("lbl_total_income_data")
        self.lbl_total_outcome_data = QtWidgets.QLabel(self.frm_details_2)
        self.lbl_total_outcome_data.setGeometry(QtCore.QRect(590, 0, 160, 40))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lbl_total_outcome_data.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_total_outcome_data.setFont(font)
        self.lbl_total_outcome_data.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_total_outcome_data.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lbl_total_outcome_data.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_total_outcome_data.setObjectName("lbl_total_outcome_data")
        self.lin_delimiter = QtWidgets.QFrame(Dialog)
        self.lin_delimiter.setGeometry(QtCore.QRect(250, 60, 1, 450))
        self.lin_delimiter.setCursor(QtGui.QCursor(QtCore.Qt.SizeHorCursor))
        self.lin_delimiter.setFrameShape(QtWidgets.QFrame.VLine)
        self.lin_delimiter.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lin_delimiter.setObjectName("lin_delimiter")
        self.lbl_wallet_name = QtWidgets.QLabel(Dialog)
        self.lbl_wallet_name.setGeometry(QtCore.QRect(250, 170, 770, 40))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(145, 195, 195))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(145, 195, 195))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(145, 195, 195))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(145, 195, 195))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.lbl_wallet_name.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_wallet_name.setFont(font)
        self.lbl_wallet_name.setAutoFillBackground(True)
        self.lbl_wallet_name.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_wallet_name.setObjectName("lbl_wallet_name")

        QtCore.QMetaObject.connectSlotsByName(Dialog)

