from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(620, 370)
        self.lbl_caption = QtWidgets.QLabel(Dialog)
        self.lbl_caption.setGeometry(QtCore.QRect(0, 0, 621, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.lbl_caption.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lbl_caption.setFont(font)
        self.lbl_caption.setAutoFillBackground(True)
        self.lbl_caption.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_caption.setObjectName("lbl_caption")
        self.btn_from_main = QtWidgets.QPushButton(Dialog)
        self.btn_from_main.setGeometry(QtCore.QRect(10, 60, 600, 41))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("data/assets/transfer_in.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_from_main.setIcon(icon)
        self.btn_from_main.setIconSize(QtCore.QSize(40, 40))
        self.btn_from_main.setAutoDefault(False)
        self.btn_from_main.setObjectName("btn_from_main")
        self.btn_to_main = QtWidgets.QPushButton(Dialog)
        self.btn_to_main.setGeometry(QtCore.QRect(10, 110, 600, 41))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("data/assets/transfer_out.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_to_main.setIcon(icon1)
        self.btn_to_main.setIconSize(QtCore.QSize(40, 40))
        self.btn_to_main.setAutoDefault(False)
        self.btn_to_main.setObjectName("btn_to_main")
        self.frm_transfer = QtWidgets.QFrame(Dialog)
        self.frm_transfer.setGeometry(QtCore.QRect(10, 180, 600, 121))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.frm_transfer.setPalette(palette)
        self.frm_transfer.setAutoFillBackground(True)
        self.frm_transfer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_transfer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_transfer.setObjectName("frm_transfer")
        self.lbl_frm_caption = QtWidgets.QLabel(self.frm_transfer)
        self.lbl_frm_caption.setGeometry(QtCore.QRect(10, 10, 581, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lbl_frm_caption.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_frm_caption.setFont(font)
        self.lbl_frm_caption.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_frm_caption.setObjectName("lbl_frm_caption")
        self.txt_rsd = QtWidgets.QLineEdit(self.frm_transfer)
        self.txt_rsd.setGeometry(QtCore.QRect(110, 60, 151, 31))
        self.txt_rsd.setObjectName("txt_rsd")
        self.lbl_rsd = QtWidgets.QLabel(self.frm_transfer)
        self.lbl_rsd.setGeometry(QtCore.QRect(40, 60, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_rsd.setFont(font)
        self.lbl_rsd.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_rsd.setObjectName("lbl_rsd")
        self.lbl_eur = QtWidgets.QLabel(self.frm_transfer)
        self.lbl_eur.setGeometry(QtCore.QRect(320, 60, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_eur.setFont(font)
        self.lbl_eur.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_eur.setObjectName("lbl_eur")
        self.txt_eur = QtWidgets.QLineEdit(self.frm_transfer)
        self.txt_eur.setGeometry(QtCore.QRect(390, 60, 151, 31))
        self.txt_eur.setObjectName("txt_eur")
        self.btn_save = QtWidgets.QPushButton(Dialog)
        self.btn_save.setGeometry(QtCore.QRect(420, 330, 93, 28))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("data/assets/ok.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_save.setIcon(icon2)
        self.btn_save.setAutoDefault(False)
        self.btn_save.setObjectName("btn_save")
        self.btn_cancel = QtWidgets.QPushButton(Dialog)
        self.btn_cancel.setGeometry(QtCore.QRect(520, 330, 93, 28))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("data/assets/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_cancel.setIcon(icon3)
        self.btn_cancel.setAutoDefault(False)
        self.btn_cancel.setObjectName("btn_cancel")

        QtCore.QMetaObject.connectSlotsByName(Dialog)
