from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1060, 430)
        self.frm_info = QtWidgets.QFrame(Dialog)
        self.frm_info.setGeometry(QtCore.QRect(0, 0, 250, 200))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.frm_info.setPalette(palette)
        self.frm_info.setAutoFillBackground(True)
        self.frm_info.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_info.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_info.setObjectName("frm_info")
        self.lbl_info_user_caption = QtWidgets.QLabel(self.frm_info)
        self.lbl_info_user_caption.setGeometry(QtCore.QRect(10, 10, 201, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lbl_info_user_caption.setPalette(palette)
        self.lbl_info_user_caption.setObjectName("lbl_info_user_caption")
        self.lbl_info_user_name = QtWidgets.QLabel(self.frm_info)
        self.lbl_info_user_name.setGeometry(QtCore.QRect(10, 40, 231, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lbl_info_user_name.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_info_user_name.setFont(font)
        self.lbl_info_user_name.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_info_user_name.setObjectName("lbl_info_user_name")
        self.lbl_info_description = QtWidgets.QLabel(self.frm_info)
        self.lbl_info_description.setGeometry(QtCore.QRect(10, 80, 231, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lbl_info_description.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_info_description.setFont(font)
        self.lbl_info_description.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lbl_info_description.setWordWrap(True)
        self.lbl_info_description.setObjectName("lbl_info_description")
        self.chk_show_password = QtWidgets.QCheckBox(self.frm_info)
        self.chk_show_password.setGeometry(QtCore.QRect(20, 150, 221, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.chk_show_password.setPalette(palette)
        self.chk_show_password.setObjectName("chk_show_password")
        self.frm_options = QtWidgets.QFrame(Dialog)
        self.frm_options.setGeometry(QtCore.QRect(250, 0, 781, 200))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.frm_options.setPalette(palette)
        self.frm_options.setAutoFillBackground(True)
        self.frm_options.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_options.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_options.setObjectName("frm_options")
        self.lbl_item_caption = QtWidgets.QLabel(self.frm_options)
        self.lbl_item_caption.setGeometry(QtCore.QRect(0, 0, 761, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lbl_item_caption.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl_item_caption.setFont(font)
        self.lbl_item_caption.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_item_caption.setObjectName("lbl_item_caption")
        self.lbl_item_web_page = QtWidgets.QLabel(self.frm_options)
        self.lbl_item_web_page.setGeometry(QtCore.QRect(10, 50, 581, 31))
        self.lbl_item_web_page.setWordWrap(True)
        self.lbl_item_web_page.setObjectName("lbl_item_web_page")
        self.lbl_item_description = QtWidgets.QLabel(self.frm_options)
        self.lbl_item_description.setGeometry(QtCore.QRect(10, 100, 581, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_item_description.setFont(font)
        self.lbl_item_description.setWordWrap(True)
        self.lbl_item_description.setObjectName("lbl_item_description")
        self.lbl_username = QtWidgets.QLabel(self.frm_options)
        self.lbl_username.setGeometry(QtCore.QRect(10, 170, 311, 21))
        self.lbl_username.setObjectName("lbl_username")
        self.lbl_password = QtWidgets.QLabel(self.frm_options)
        self.lbl_password.setGeometry(QtCore.QRect(350, 170, 311, 21))
        self.lbl_password.setObjectName("lbl_password")
        self.line = QtWidgets.QFrame(self.frm_options)
        self.line.setGeometry(QtCore.QRect(10, 160, 761, 16))
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.lbl_created = QtWidgets.QLabel(self.frm_options)
        self.lbl_created.setGeometry(QtCore.QRect(10, 145, 121, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lbl_created.setPalette(palette)
        self.lbl_created.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_created.setObjectName("lbl_created")
        self.lbl_created_data = QtWidgets.QLabel(self.frm_options)
        self.lbl_created_data.setGeometry(QtCore.QRect(140, 145, 311, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lbl_created_data.setPalette(palette)
        self.lbl_created_data.setObjectName("lbl_created_data")
        self.tbl_data = QtWidgets.QTableWidget(Dialog)
        self.tbl_data.setGeometry(QtCore.QRect(0, 230, 1031, 192))
        self.tbl_data.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tbl_data.setObjectName("tbl_data")
        self.tbl_data.setColumnCount(0)
        self.tbl_data.setRowCount(0)
        self.tbl_data.verticalHeader().setDefaultSectionSize(25)
        self.tbl_data.verticalHeader().setMinimumSectionSize(20)
        self.btn_show_all = QtWidgets.QPushButton(Dialog)
        self.btn_show_all.setGeometry(QtCore.QRect(0, 205, 111, 25))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("data/assets/reset_view.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_show_all.setIcon(icon)
        self.btn_show_all.setObjectName("btn_show_all")
        self.btn_view = QtWidgets.QPushButton(Dialog)
        self.btn_view.setGeometry(QtCore.QRect(670, 205, 75, 25))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("data/assets/view.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_view.setIcon(icon1)
        self.btn_view.setObjectName("btn_view")
        self.btn_edit = QtWidgets.QPushButton(Dialog)
        self.btn_edit.setGeometry(QtCore.QRect(750, 205, 75, 25))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("data/assets/edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_edit.setIcon(icon2)
        self.btn_edit.setObjectName("btn_edit")
        self.btn_delete = QtWidgets.QPushButton(Dialog)
        self.btn_delete.setGeometry(QtCore.QRect(830, 205, 75, 25))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("data/assets/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_delete.setIcon(icon3)
        self.btn_delete.setObjectName("btn_delete")
        self.btn_add_new = QtWidgets.QPushButton(Dialog)
        self.btn_add_new.setGeometry(QtCore.QRect(940, 205, 111, 25))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("data/assets/new1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_add_new.setIcon(icon4)
        self.btn_add_new.setObjectName("btn_add_new")
        self.lbl_records = QtWidgets.QLabel(Dialog)
        self.lbl_records.setGeometry(QtCore.QRect(420, 205, 215, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lbl_records.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_records.setFont(font)
        self.lbl_records.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_records.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_records.setObjectName("lbl_records")
        self.btn_filter_apply = QtWidgets.QPushButton(Dialog)
        self.btn_filter_apply.setGeometry(QtCore.QRect(280, 205, 111, 25))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("data/assets/table_view.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_filter_apply.setIcon(icon5)
        self.btn_filter_apply.setObjectName("btn_filter_apply")
        self.txt_filter = QtWidgets.QLineEdit(Dialog)
        self.txt_filter.setGeometry(QtCore.QRect(110, 205, 161, 25))
        self.txt_filter.setObjectName("txt_filter")

        QtCore.QMetaObject.connectSlotsByName(Dialog)
