from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 380)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        Dialog.setPalette(palette)
        self.lbl_caption = QtWidgets.QLabel(Dialog)
        self.lbl_caption.setGeometry(QtCore.QRect(0, 85, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_caption.setFont(font)
        self.lbl_caption.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_caption.setObjectName("lbl_caption")
        self.lbl_title = QtWidgets.QLabel(Dialog)
        self.lbl_title.setGeometry(QtCore.QRect(0, 10, 801, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lbl_title.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lbl_title.setFont(font)
        self.lbl_title.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_title.setObjectName("lbl_title")
        self.txt_caption = QtWidgets.QLineEdit(Dialog)
        self.txt_caption.setGeometry(QtCore.QRect(210, 80, 580, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txt_caption.setFont(font)
        self.txt_caption.setText("")
        self.txt_caption.setObjectName("txt_caption")
        self.txt_web_page = QtWidgets.QLineEdit(Dialog)
        self.txt_web_page.setGeometry(QtCore.QRect(210, 120, 580, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.txt_web_page.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txt_web_page.setFont(font)
        self.txt_web_page.setText("")
        self.txt_web_page.setObjectName("txt_web_page")
        self.lbl_web_page = QtWidgets.QLabel(Dialog)
        self.lbl_web_page.setGeometry(QtCore.QRect(0, 125, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_web_page.setFont(font)
        self.lbl_web_page.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_web_page.setObjectName("lbl_web_page")
        self.lbl_description = QtWidgets.QLabel(Dialog)
        self.lbl_description.setGeometry(QtCore.QRect(0, 165, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_description.setFont(font)
        self.lbl_description.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_description.setObjectName("lbl_description")
        self.txt_username = QtWidgets.QLineEdit(Dialog)
        self.txt_username.setGeometry(QtCore.QRect(210, 255, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txt_username.setFont(font)
        self.txt_username.setText("")
        self.txt_username.setObjectName("txt_username")
        self.lbl_username = QtWidgets.QLabel(Dialog)
        self.lbl_username.setGeometry(QtCore.QRect(0, 260, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_username.setFont(font)
        self.lbl_username.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_username.setObjectName("lbl_username")
        self.txt_password = QtWidgets.QLineEdit(Dialog)
        self.txt_password.setGeometry(QtCore.QRect(210, 290, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txt_password.setFont(font)
        self.txt_password.setText("")
        self.txt_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txt_password.setClearButtonEnabled(False)
        self.txt_password.setObjectName("txt_password")
        self.lbl_password = QtWidgets.QLabel(Dialog)
        self.lbl_password.setGeometry(QtCore.QRect(0, 295, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_password.setFont(font)
        self.lbl_password.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_password.setObjectName("lbl_password")
        self.btn_show_password = QtWidgets.QPushButton(Dialog)
        self.btn_show_password.setGeometry(QtCore.QRect(520, 290, 31, 31))
        self.btn_show_password.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("data/assets/show_all.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_show_password.setIcon(icon)
        self.btn_show_password.setObjectName("btn_show_password")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(50, 50, 741, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.btnbox = QtWidgets.QDialogButtonBox(Dialog)
        self.btnbox.setGeometry(QtCore.QRect(630, 350, 156, 23))
        self.btnbox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.btnbox.setObjectName("btnbox")
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setGeometry(QtCore.QRect(50, 330, 741, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.txt_description = QtWidgets.QTextEdit(Dialog)
        self.txt_description.setGeometry(QtCore.QRect(210, 160, 580, 81))
        self.txt_description.setObjectName("txt_description")

        QtCore.QMetaObject.connectSlotsByName(Dialog)
